BEGIN;

ALTER TABLE "ApiKey" ENABLE ELECTRIC;
ALTER TABLE "DailyLog" ENABLE ELECTRIC;
ALTER TABLE "DailyLogItem" ENABLE ELECTRIC;
ALTER TABLE "Equipment" ENABLE ELECTRIC;
ALTER TABLE "EquipmentProperty" ENABLE ELECTRIC;
ALTER TABLE "EquipmentPropertyValue" ENABLE ELECTRIC;
ALTER TABLE "Feedback" ENABLE ELECTRIC;
ALTER TABLE "File" ENABLE ELECTRIC;
ALTER TABLE "FileProperty" ENABLE ELECTRIC;
ALTER TABLE "FilePropertyValue" ENABLE ELECTRIC;
ALTER TABLE "Image" ENABLE ELECTRIC;
ALTER TABLE "LocationEntry" ENABLE ELECTRIC;
ALTER TABLE "Project" ENABLE ELECTRIC;
ALTER TABLE "ProjectProperty" ENABLE ELECTRIC;
ALTER TABLE "ProjectPropertyValue" ENABLE ELECTRIC;
ALTER TABLE "Task" ENABLE ELECTRIC;
ALTER TABLE "TaskProperty" ENABLE ELECTRIC;
ALTER TABLE "TaskPropertyValue" ENABLE ELECTRIC;
ALTER TABLE "TaskStatus" ENABLE ELECTRIC;
ALTER TABLE "Tenant" ENABLE ELECTRIC;
ALTER TABLE "TenantUser" ENABLE ELECTRIC;
ALTER TABLE "TimeBlock" ENABLE ELECTRIC;
ALTER TABLE "User" ENABLE ELECTRIC;
ALTER TABLE "UserTask" ENABLE ELECTRIC;

COMMIT;
